source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

target 'BaiSiBuDeJie' do

pod 'AFNetworking', '~> 3.0.0-beta.2'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'pop'

end

#target :BaiSiBuDeJieTests, :exclusive => true do
  # pod 'Kiwi'
#end
